#!/usr/bin/python

import sys
from launchpadlib.launchpad import Launchpad

pkg = sys.argv[1]
ver = sys.argv[2]

cachedir = "/home/mschlaef/.launchpadlib/cache/"
launchpad = Launchpad.login_with('copypackages', 'edge', cachedir)

testing_archive = launchpad.people['tuxonice'].getPPAByName(name='staging')
stable_archive = launchpad.people['tuxonice'].getPPAByName(name='ppa')

stable_archive.copyPackage(source_name=pkg,version=ver,from_archive=testing_archive,to_pocket='release',include_binaries=True)

# example for request deletion of all packages in lucid
# l = stable_archive.getPublishedSources(distro_series='https://api.launchpad.net/1.0/ubuntu/lucid')
# len(l)
# for p in l:
#      p.requestDeletion()

