#!/bin/bash

for RELEASE in precise trusty vivid wily xenial; do
  echo "checking updates for UBUNTU $RELEASE:"
  ubuntu-current-linux $RELEASE
  echo
  cd linux
  ppa-rebuild linux $RELEASE ppa:tuxonice/staging
  cd ..
  cd linux-meta
  ppa-rebuild linux-meta $RELEASE ppa:tuxonice/staging
  cd ..
  if [ $RELEASE = precise ]; then
    cd linux-lbm
    ppa-rebuild linux-lbm $RELEASE ppa:tuxonice/staging
    cd ..
  fi
  echo
done

