#!/bin/bash

for RELEASE in trusty xenial zesty artful; do
  echo "checking updates for UBUNTU $RELEASE:"
  ubuntu-current-linux $RELEASE
  echo
  cd linux
  ppa-rebuild linux $RELEASE ppa:tuxonice/staging
  cd ..
  cd linux-meta
  ppa-rebuild linux-meta $RELEASE ppa:tuxonice/staging
  cd ..
  echo
done

