#!/bin/bash

UBUNTU=$1

# rename flavours to contain -tuxonice in debian.master/config
for i in `find debian.master/config | grep "config.flavour"`; do
  git mv $i $i-tuxonice;
done
git commit -s -m "TuxOnIce: [Config] Rename flavours to contain -tuxonice in debian.master/config"

# add tuxonice specific config to each flavour
for i in `find debian.master/config | grep "config.flavour"`; do
  cat ../tuxonice-ppa-scripts/config/tuxonice-$UBUNTU.config >> $i;
done
git commit -a -s -m "TuxOnIce: [Config] Add tuxonice specific config to each flavour"

if [ $UBUNTU = zesty -o $UBUNTU = artful ]; then
  # disable KASLR since it breaks TuxOnIce 
  sed -i 's/CONFIG_RANDOMIZE_BASE=y/# CONFIG_RANDOMIZE_BASE is not set/' debian.master/config/config.common.ubuntu 
  git commit -a -s -m "TuxOnIce: [Config] Disable CONFIG_RANDOMIZE_BASE (KASLR) since it breaks TuxOnIce (github issue #29)"
fi

# rename flavours to contain -tuxonice in debian.master/control.d
for i in `find debian.master/control.d | grep \/vars\.`; do
  git mv $i $i-tuxonice;
done
for i in `find debian.master/control.d | grep "inclusion-list"`; do
  git mv $i `echo $i | sed 's/\.inclusion-list/-tuxonice.inclusion-list/'`;
done
git commit -s -m "TuxOnIce: [Packaging] Rename flavours to contain -tuxonice in debian.master/control.d"

# add -tuxonice to flavours in debian.master/rules.d
for i in debian.master/rules.d/*; do
  sed -i '/^flavours/s/\( [a-z0-9-][a-z0-9-]*\)/\1-tuxonice/g' $i
done
git commit -a -s -m "TuxOnIce: [Packaging] Add -tuxonice to flavours in debian.master/rules.d"

# add -tuxonice to flavours in debian.master/d-i/kernel-versions.in
if [ $UBUNTU = zesty -o $UBUNTU = artful ]; then
  sed -i -e '/^#/!s/\(\t\+\)/-tuxonice\1/3' debian.master/d-i/kernel-versions
  git commit -a -s -m "TuxOnIce: [Packaging] Add -tuxonice to flavours in debian.master/d-i/kernel-versions"
else
  sed -i -e '/^#/!s/\(\t\+\)/-tuxonice\1/3' -e '/^#/!s/\(\t\+\)/-tuxonice\1/4' debian.master/d-i/kernel-versions.in
  git commit -a -s -m "TuxOnIce: [Packaging] Add -tuxonice to flavours in debian.master/d-i/kernel-versions.in"
fi

# add -tuxonice to flavours in getabis file
sed -i '/getall /s/\( [a-z0-9-][a-z0-9-]*\)/\1-tuxonice/g' debian/scripts/misc/getabis
git commit -a -s -m "TuxOnIce: [Packaging] Add -tuxonice to flavours in getabis file"

# add skipabi=true and skipmodules=true to build options
sed -i 's/^AUTOBUILD=/skipabi=true\nskipmodule=true\nAUTOBUILD=/' debian/rules.d/0-common-vars.mk
git commit -a -s -m "TuxOnIce: [Packaging] Add skipabi=true and skipmodules=true to build options"

