#!/bin/bash

UBUNTU=$1
KERNEL=$2
MAJOR=$3
MINOR=$4
PPA=$5
DPUT=$6

# clean, pull and checkout current Ubuntu kernel
git reset --hard
git clean -xdf
git fetch --all --tags
git checkout Ubuntu-$KERNEL-$MAJOR.$MINOR

# add tuxonice to kernel-versions.in
# file: debian.master/d-i/kernel-versions.in
cp debian/d-i/kernel-versions.in debian/d-i/kernel-versions.in.tmp
cat debian/d-i/kernel-versions.in.tmp | \
  grep -v ^$ | grep -v ^# | \
    awk '{ print $1 "\t" $2 "\t" $3"-tuxonice" "\t" $4"-tuxonice" "\t" $5 "\t" $6 "\t" $7 }' \
    > debian/d-i/kernel-versions.in
rm debian/d-i/kernel-versions.in.tmp

# add tuxonice to vars.$FLAVOUR
# files: debian.master/control.d/vars.$FLAVOUR
for i in `find debian | grep \/vars\.`; do
  mv $i $i-tuxonice;
done

# add tuxonice to $FLAVOUR.mk
# files: debian.master/rules.d/$FLAVOUR.mk
cp -a debian/rules.d/ debian/rules.d.tmp
for i in debian/rules.d.tmp/*; do
  sed '/^flavours/s/\( [a-z0-9-][a-z0-9-]*\)/\1-tuxonice/g' $i \
    > `echo $i | sed 's/.tmp//g'`
done
rm -rf debian/rules.d.tmp

# changelog
cp debian/changelog debian/changelog.old
echo "linux-backports-modules-$KERNEL ($KERNEL-$MAJOR.$MINOR~ppa$PPA) $UBUNTU; urgency=low" > debian/changelog
echo "" >> debian/changelog
echo "  * TuxOnIce enabled package." >> debian/changelog
echo "" >> debian/changelog
echo " -- "`bzr whoami`"  "`date -R` >> debian/changelog
echo "" >> debian/changelog
cat debian/changelog.old >> debian/changelog
rm debian/changelog.old

# build package and upload
fakeroot debian/rules clean
debuild -S -sd -I.git -I.gitignore -i'\.git.*'
dput $DPUT ../linux-backports-modules-${KERNEL}_$KERNEL-$MAJOR.$MINOR~ppa${PPA}_source.changes
rm -f ../linux-backports-modules-${KERNEL}_$KERNEL-$MAJOR.$MINOR~ppa${PPA}*

