#!/bin/bash

UBUNTU=$1
KERNEL=$2
MAJOR=$3
MINOR=$4

#HOSTS="lp github"
HOSTS="github"

for i in $HOSTS; do
    git push $i $UBUNTU:$UBUNTU --force
    git push $i Ubuntu-$KERNEL-$MAJOR.$MINOR-tuxonice
done

