#!/bin/bash

UBUNTU=$1
KERNEL=$2
MAJOR=$3
MINOR=$4
PPA=$5
DPUT=$6
MERGE=$7

LINUX=`echo $KERNEL | sed 's/\.[0-9]*$//'`

# cleanup git repository
git reset --hard
git clean -xdf
git fetch --all --tags

if [ -z $MERGE ]; then

    # checkout ubuntu-kernel-with-tuxonice release branch and merge new ubuntu release 
    git checkout $UBUNTU
    git merge Ubuntu-$KERNEL-$MAJOR.$MINOR -S -m "Merge tag 'Ubuntu-$KERNEL-$MAJOR.$MINOR'"
    if [ $? -ne 0 ]; then
        echo "Merge failed! Please resolve the conflicts, commit and rerun $0"
        exit 1;
    fi

else

    # checkout ubuntu release, create branch, merge tuxonice and start ubuntu-kernel-with-tuxonice release
    git checkout Ubuntu-$KERNEL-$MAJOR.$MINOR
    git branch -D $UBUNTU
    git checkout -b $UBUNTU
    git merge $MERGE -S -m "TuxOnIce: Merge branch 'tuxonice-$LINUX' of git://github.com/NigelCunningham/tuxonice-kernel.git"
    if [ $? -ne 0 ]; then
        echo "Merge failed! Please resolve the conflicts, commit and rerun $0"
        exit 1;
    fi
    ppa-linux-tuxonice-start $UBUNTU

fi

# tag this ubuntu-kernel-with-tuxonice release
git tag -s -a Ubuntu-$KERNEL-$MAJOR.$MINOR-tuxonice -m "Ubuntu-$KERNEL-$MAJOR.$MINOR with TuxOnIce"

# edit debian/changelog
dch -b -v "$KERNEL-$MAJOR.$MINOR~ppa$PPA" -D $UBUNTU "Add TuxOnIce" -c debian.master/changelog

# build package and upload
fakeroot debian/rules clean
debuild -S -sd
dput $DPUT ../linux_$KERNEL-$MAJOR.$MINOR~ppa${PPA}_source.changes
rm -f ../linux_$KERNEL-$MAJOR.$MINOR~ppa${PPA}*

# push to github and launchpad
ppa-git-push $UBUNTU $KERNEL $MAJOR $MINOR

