#!/bin/sh

. "${PM_FUNCTIONS}"

case $1 in
    suspend|hibernate)
	remove_parameters --quirk-no-chvt
	if [ -f "/sys/power/tuxonice/user_interface/enable_escape" ]; then
	    echo 1 > /sys/power/tuxonice/user_interface/enable_escape
	fi
	;;
    *)
	exit 0
	;;
esac
