#! /bin/sh -eu
#
# Pre-removal hook script for hibernate
#
# Originally written by Cameron Patrick, 2004 and released to the public domain.
# Modified by martin f. krafft.
#
# Copyright © martin f. krafft <madduck@debian.org>
# Released under the terms of the Artistic Licence 2.0
#
# $Id$
#

if [ "${1:-}" = remove ]; then
  rmdir --ignore-fail-on-non-empty --parents \
    /usr/local/share/hibernate/scriptlets.d 2>/dev/null || :
fi

# See #369953
set +u
#DEBHELPER#
set -u
