#!/usr/bin/python

import sys
from launchpadlib.launchpad import Launchpad

pkg = sys.argv[1]
ver = sys.argv[2]

cachedir = "/home/mschlaef/.launchpadlib/cache/"
launchpad = Launchpad.login_with('copypackages', 'edge', cachedir)

from_archive = launchpad.people['tuxonice'].getPPAByName(name='tuxonice-testing')
to_archive = launchpad.people['tuxonice'].getPPAByName(name='ppa')

to_archive.syncSource(source_name=pkg,version=ver,from_archive=from_archive,to_pocket='release',include_binaries=True)


