#!/bin/bash

UBUNTU=$1
KERNEL=$2
MAJOR=$3
MINOR=$4
PPA=$5
DPUT=$6

echo "Building linux $KERNEL-$MAJOR.$MINOR~ppa$PPA for $UBUNTU with TuxOnIce"

# fetch and clean
cd linux
git fetch --all
git reset --hard
git clean -xdf

# checkout tuxonice release branch 
git checkout ubuntu-linux-$UBUNTU-tuxonice

# merge new ubuntu release 
git merge Ubuntu-$KERNEL-$MAJOR.$MINOR -S -m "Merge tag 'Ubuntu-$KERNEL-$MAJOR.$MINOR'"
if [ $? -ne 0 ]; then
  exit 1;
fi

# tag this tuxonice release
git tag Ubuntu-$KERNEL-$MAJOR.$MINOR-tuxonice

# edit debian/changelog
dch -b -v "$KERNEL-$MAJOR.$MINOR~ppa$PPA" -D $UBUNTU "Add TuxOnIce." -c debian.master/changelog
#git commit -a -s -m "TuxOnIce: [Packaging] Add tuxonice to debian/changelog"

# build package and upload
fakeroot debian/rules clean
debuild -S -sd
#dput $DPUT ../linux_$KERNEL-$MAJOR.$MINOR~ppa${PPA}_source.changes
cd ..

