#!/bin/bash

UBUNTU=$1
#KERNEL=$2
MAJOR=$2
MINOR=$3
PPA=$4
UVER=$5
DPUT=$6

# clean, pull and checkout
ubuntu-git-clean
git pull

cp -a ../tuxoniceppa/ubuntu-hibernate-script/* .

# edit changelog
cp debian/changelog debian/changelog.old
echo "hibernate ($MAJOR$MINOR~ppa$PPA~$UBUNTU$UVER) $UBUNTU; urgency=low" > debian/changelog
echo "" >> debian/changelog
echo "  * New upstream GIT snapshot." >> debian/changelog
echo "" >> debian/changelog
echo " -- "`bzr whoami`"  "`date -R` >> debian/changelog
echo "" >> debian/changelog
cat debian/changelog.old >> debian/changelog
rm debian/changelog.old

# build package and upload
debuild -S -sd -I.git -I.gitignore -i'\.git.*'
#echo tuxonice-userui_$MAJOR$MINOR~ppa$PPA~$UBUNTU$UVER\_source.changes
dput $DPUT ../hibernate_$MAJOR$MINOR~ppa$PPA~$UBUNTU$UVER\_source.changes

#ubuntu-git-clean

