#!/bin/bash

UBUNTU=$1
KERNEL=$2
MAJOR=$3
MINOR=$4
PPA=$5
DPUT=$6

DEBIAN=debian
CONTROL=control.common

cd linux-meta
echo "building $UBUNTU $KERNEL $MAJOR $MINOR $PPA $DPUT"

# clean, pull and checkout current Ubuntu kernel
git reset --hard
git clean -xdf
git fetch --all

#KERNEL=`git log $UBUNTU/master | grep "UBUNTU: Ubuntu-" | sed 's|.*[A-Za-z-]\+-\([.0-9]\+\).*|\1|' | grep "\.$MAJOR\.$MINOR$" | head -n 1 | sed "s/.$MAJOR.$MINOR//"`

git checkout Ubuntu-$KERNEL.$MAJOR.$MINOR
cd meta-source

# add tuxonice to control.d
# files: debian.master/control.d/*
cp -a $DEBIAN/control.d $DEBIAN/control.d.old
for i in $DEBIAN/control.d/*; do
  mv $i $i-tuxonice
  for j in $DEBIAN/control.d.old/*; do
    FLAVOUR=`echo $j | cut -d/ -f3`
    cp $i-tuxonice $i-tuxonice.old
    sed "s/-$FLAVOUR\([^a-z0-9-]\)/-$FLAVOUR-tuxonice\1/g" $i-tuxonice.old > $i-tuxonice;
    cp $i-tuxonice $i-tuxonice.old
    sed "s/-$FLAVOUR$/-$FLAVOUR-tuxonice/g" $i-tuxonice.old > $i-tuxonice;
  done
  rm $i-tuxonice.old
  FLAVOUR=`echo $i | cut -d/ -f3`
  cp $DEBIAN/$CONTROL $DEBIAN/$CONTROL.old
  sed "s/-$FLAVOUR\([^a-z0-9-]\)/-$FLAVOUR-tuxonice\1/g" $DEBIAN/$CONTROL.old > $DEBIAN/$CONTROL;
  cp $DEBIAN/$CONTROL $DEBIAN/$CONTROL.old
  sed "s/-$FLAVOUR$/-$FLAVOUR-tuxonice/g" $DEBIAN/$CONTROL.old > $DEBIAN/$CONTROL;
done
rm -rf $DEBIAN/control.d.old
rm $DEBIAN/$CONTROL.old

# edit changelog
cp $DEBIAN/changelog $DEBIAN/changelog.old
echo "linux-meta ($KERNEL.$MAJOR.$MINOR~ppa$PPA) $UBUNTU; urgency=low" > $DEBIAN/changelog
echo "" >> $DEBIAN/changelog
echo "  * TuxOnIce enabled package." >> $DEBIAN/changelog
echo "" >> $DEBIAN/changelog
echo " -- "`bzr whoami`"  "`date -R` >> $DEBIAN/changelog
echo "" >> $DEBIAN/changelog
cat $DEBIAN/changelog.old >> $DEBIAN/changelog
rm $DEBIAN/changelog.old

# prepare, build and upload package
fakeroot $DEBIAN/rules clean
debuild -S -sd -I.git -I.gitignore -i'\.git.*'
#echo dput $DPUT ../linux_$KERNEL-$MAJOR.$MINOR~ppa${PPA}_source.changes
dput $DPUT ../linux-meta_$KERNEL.$MAJOR.$MINOR~ppa${PPA}_source.changes
cd ..
cd ..

