#!/bin/bash

UBUNTU=$1
KERNEL=$2
MAJOR=$3
MINOR=$4
MERGE=$5

LINUX=`echo $KERNEL | sed 's/\.[0-9]*$//'`

# cleaup git repository
git reset --hard
git clean -xdf
git fetch --all

# checkout ubuntu release
git checkout Ubuntu-$KERNEL-$MAJOR.$MINOR

# create new ubuntu-kernel-with-tuxonice release branch
git branch -D $UBUNTU
git checkout -b $UBUNTU

# merge tuxonice (branch, tag or commit)
git merge $MERGE -S -m "TuxOnIce: Merge branch 'tuxonice-$LINUX' of git://github.com/NigelCunningham/tuxonice-kernel.git"

