#!/bin/bash

TOI=$1
DEMO=$2

for RELEASE in vivid utopic trusty precise lucid; do
  echo "checking updates for UBUNTU $RELEASE:"
  ubuntu-current $RELEASE
  echo
  if [ "$RELEASE" == "lucid" ]; then
    ppa-rebuild-linux $RELEASE ppa:tuxonice/tuxonice-testing 3.2 $DEMO
  else
    ppa-rebuild-linux $RELEASE ppa:tuxonice/tuxonice-testing $TOI $DEMO
  fi
  ppa-rebuild-linux-meta $RELEASE ppa:tuxonice/tuxonice-testing $DEMO
  if [ "$RELEASE" == "lucid" ]; then
    ppa-rebuild-linux-lbm $RELEASE ppa:tuxonice/tuxonice-testing $DEMO
  fi
  if [ "$RELEASE" == "precise" ]; then
    ppa-rebuild-linux-lbm $RELEASE ppa:tuxonice/tuxonice-testing $DEMO
  fi
  echo
  echo
done

