#!/bin/bash

# usage: ppa-rebuild-linux-meta trusty ppa:tuxonice/daily

UBUNTU=$1
DPUT=$2

ubuntu-current-linux $UBUNTU linux-meta > ~tmp
TAG=`cat ~tmp | grep -v -e proposed -e tuxonice | sort | tail -n 1`
PPATAG=`cat ~tmp | grep ppa:tuxonice | tail -n 1`
VERSION=`echo $TAG | awk '{print $1}'`
PPAVERSION=`echo $PPATAG | awk '{print $1}'`
rm ~tmp

KERNEL=`echo $VERSION | sed "s/^\([0-9]*.[0-9]*.[0-9]*\).*/\1/"`
MAJOR=`echo $VERSION | sed "s/^[0-9]*.[0-9]*.[0-9]*.\([0-9]*\).[0-9]*/\1/"`
MINOR=`echo $VERSION | sed "s/^[0-9]*.[0-9]*.[0-9]*.[0-9]*.\([0-9]*\)/\1/"`

echo "$VERSION $UBUNTU"
echo "$TAG $PPATAG $VERSION $PPAVERSION $DPUT"
echo "$KERNEL $MAJOR $MINOR"

PPAVERSION=`echo $PPAVERSION | cut -d~ -f1`

echo "checking PPA < UBUNTU ..."
echo "  $PPAVERSION < $VERSION"
if dpkg --compare-versions "$PPAVERSION" lt "$VERSION"; then
  REBUILD=true
  PPA=1
fi

if [ -z "$REBUILD" ]; then
  echo "not rebuilding $UBUNTU linux-meta-tuxonice: $VERSION for $DPUT"
  exit 0
fi

echo "rebuilding $UBUNTU linux-meta-tuxonice: $VERSION~ppa$PPA for $DPUT:"
echo "  ppa-linux-meta-tuxonice $UBUNTU $MAJOR $MINOR $PPA $DPUT"
ppa-linux-meta-tuxonice $UBUNTU $MAJOR $MINOR $PPA $DPUT
cd ..

