#!/bin/bash

UBUNTU=$1
KERNEL=$2
MAJOR=$3
MINOR=$4
PPA=$5
DPUT=$6

cd linux
echo "Building linux $KERNEL-$MAJOR.$MINOR~ppa$PPA for $UBUNTU with TuxOnIce"

# cleanup git repository
git reset --hard
git clean -xdf
git fetch --all

# checkout ubuntu-kernel-with-tuxonice release branch 
git checkout $UBUNTU

# merge new upstream ubuntu release 
git merge Ubuntu-$KERNEL-$MAJOR.$MINOR -S -m "Merge tag 'Ubuntu-$KERNEL-$MAJOR.$MINOR'"
if [ $? -ne 0 ]; then
    echo "Merge failed! Please resolve the conflicts, then commit and rerun $0"
    exit 1;
fi

# tag this ubuntu-kernel-with-tuxonice release
git tag -s -a Ubuntu-$KERNEL-$MAJOR.$MINOR-tuxonice -m "Ubuntu-$KERNEL-$MAJOR.$MINOR with TuxOnIce"

# edit debian/changelog
dch -b -v "$KERNEL-$MAJOR.$MINOR~ppa$PPA" -D $UBUNTU "Add TuxOnIce." -c debian.master/changelog
#git commit -a -s -m "TuxOnIce: [Packaging] Add tuxonice to debian/changelog"

# build package and upload
fakeroot debian/rules clean
debuild -S -sd
dput $DPUT ../linux_$KERNEL-$MAJOR.$MINOR~ppa${PPA}_source.changes
cd ..

