#!/bin/bash

LOGS=1000
VERSION=$1

#git log -n $LOGS --parents | \
#  grep -i -e ^commit -e "merge branch" -e "bump version to" | \
#  grep -i -e "bump version to $VERSION" -A 1000 | \
#  grep -i -e "merge branch" -B 1 | \
#  grep -v "\-\-" | head -n 1 | awk '{ print $4 }'

#git log -n $LOGS --parents | \
#  grep -i -e ^commit -e "bump version to" | \
#  grep -i -e "bump version to $VERSION" -B 1 | \
#  grep -v "\-\-" | head -n 1 | awk '{ print $2 }'

git checkout TuxOnIce-$VERSION 2>/dev/null >/dev/null

if [ "$?" != 0 ]; then
  exit;
fi

git log -n 1000 --parents | grep -i -e "^commit" -e "merge branch" | grep -i -e "merge branch" -B 1 | grep -v "\-\-" | head -n 1 | awk '{ print $4 }'

git log -n 1 | head -n 1 | awk '{ print $2 }'

#git tag -v TuxOnIce-3.2-rc2 2>/dev/null | head -n 1 | awk '{print $2}'

tuxonice-git-clean 2>/dev/null >/dev/null

