#!/bin/bash

RELEASE=$1

if [ "$RELEASE" = natty ]; then
  echo 2.6.38
fi

if [ "$RELEASE" = maverick ]; then
  echo 2.6.35
fi

if [ "$RELEASE" = lucid ]; then
  echo 2.6.32
fi

if [ "$RELEASE" = karmic ]; then
  echo 2.6.31
fi

if [ "$RELEASE" = jaunty ]; then
  echo 2.6.28
fi

