#!/bin/bash

for RELEASE in natty maverick lucid karmic jaunty; do
  echo $RELEASE
  cd ubuntu-$RELEASE
  ubuntu-git-clean
  cd ..
  cd ubuntu-$RELEASE-meta
  ubuntu-git-clean
  cd ..
  cd ubuntu-$RELEASE-lbm
  ubuntu-git-clean
  cd ..
  if [ "$RELEASE" = jaunty ]; then
    cd ubuntu-$RELEASE-lrm
    ubuntu-git-clean
    cd ..
  fi
done

