#!/bin/bash

RELEASE=$1

if [ "$RELEASE" = trusty ]; then
  echo 3.13.0
fi

if [ "$RELEASE" = saucy ]; then
  echo 3.11.0
fi

if [ "$RELEASE" = raring ]; then
  echo 3.8.0
fi

if [ "$RELEASE" = quantal ]; then
  echo 3.5.0
fi

if [ "$RELEASE" = precise ]; then
  echo 3.2.0
fi

if [ "$RELEASE" = oneiric ]; then
  echo 3.0.0
fi

if [ "$RELEASE" = natty ]; then
  echo 2.6.38
fi

if [ "$RELEASE" = maverick ]; then
  echo 2.6.35
fi

if [ "$RELEASE" = lucid ]; then
  echo 2.6.32
fi

if [ "$RELEASE" = karmic ]; then
  echo 2.6.31
fi

if [ "$RELEASE" = jaunty ]; then
  echo 2.6.28
fi

